shear:
  g: 0.02

metadetect:
  model: wmom
  metacal:
    psf: fitgauss
    types: [noshear, 1p, 1m, 2p, 2m]
    use_noise_image: true
    # step: 0.01
  weight:
    fwhm: 1.2  # arcsec
  meds:
    box_padding: 2
    box_type: iso_radius
    max_box_size: 48
    min_box_size: 48
    rad_fac: 2
    rad_min: 4
